apiVersion: apps/v1
kind: Deployment
metadata:
  name: werewolf-deployment
spec:
  selector:
      matchLabels:
        app: werewolf
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: werewolf
    spec:
      containers:
        - name: werewolf
          image: gcr.io/chat-251918/werewolf-image:0.2
          command: ["python", "werewolf/werewolf.py"]
          ports:
            - containerPort: 5001
