apiVersion: v1
kind: Service
metadata:
  name: werewolf-service
  labels:
    app: werewolf
spec:
  type: NodePort
  ports:
    - name: ww-port
      port: 5001
      nodePort: 30011
      targetPort: 5001
  selector:
    app: werewolf
